### ISSUE TITLE
Seeing black overlay on LeftSide of Image. Unintended.

### ISSUE THREAD

**Issue by Monte9** [brentvatne/cube-transition-example#1]
Hey Brent. 

Tried this recently and noticed an unintended black overlap on the left side. 

I would think this has to do with some change in core react native that were added since you wrote this the first time. 

Check out the [expo example](https://getexponent.com/@community/cube-transition-example) to see what I am talking about. 

Since I barely understand the code, I could mess around with the number and see if I can fix it. But before I did that, I was wondering if you might have some pointers for me as to what could be causing this? 

Thanks.

**Comment by Monte9** [comment]
![screenshot_20170615-104318](https://user-images.githubusercontent.com/7840686/27194739-95900492-51b8-11e7-93c2-ba7335a76014.png)

**Comment by neo125874** [comment]
@Monte9 hi, i try the example too, did you solve the issue?

**Comment by Monte9** [comment]
@neo125874 nope. Don't know where to start. lol
